version: '2'
services:
  users-service:
    container_name: 'users-service'
    build: './'
    ports:
      - 9005:4444
    volumes:
      - './api:$HOME/go/src/github.com/iafoosball/users-service'
    links:
      - "arangodb"
    depends_on:
      - 'arangodb'
  arangodb:
    container_name: 'users-arangodb'
    image: arangodb/arangodb:3.3.11
    ports:
      - 9006:8529
    environment:
      - ARANGO_ROOT_PASSWORD=iafoosball@users for the win
    volumes:
      - /var/lib/arangodb-users-persistent:/var/lib/arangodb3

  swagger-ui:
    container_name: "swagger"
    build: './swagger-ui/'
    ports:
      - 9007:8080